version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-docker
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    build: ./backend
    container_name: backend-docker

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"

volumes:
  dbdata:
