version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-docker
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    build: ./backend
    container_name: backend-docker

  database:
    image: mariadb:latest
    container_name: database-docker
    restart: always
    command: --defaut-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-phpmyadmin

volumes:
  dbdata:
