version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-docker
    ports:
      - "8282:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    build: ./backend
    container_name: backend-docker
    restart: unless-stopped

  database:
    container_name: database-docker
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: mon_agence_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3306:3306"
